---
resources:
- name: src
  type: git
  source:
    uri: git@github.com:kaligan/concourse-node-6.git
    branch: master
    private_key: {{git_private_key}}
- name: img
  type: docker-image
  source:
    repository: docker-admobile.artifactory.appcarousel.com/appdirect/node-6
    username: {{docker_username}}
    password: {{docker_password}}
jobs:
- name: build-image
  plan:
  - get: src
    trigger: true
  - put: img
    params: {build: src}
    get_params: {rootfs: true}